spring:
  application:
    name: eshop-zuul-lb
  cloud:
    config:
      uri: http://localhost:8761
zuul:
  routes:
    eshop-customer-client:
      path: /customer/**
      serviceId: eshop-customer-client
      stripPrefix: true
