spring:
  application:
    name: eshop-shopping-client
  cloud:
    config:
      uri: http://localhost:8761
sleuth:
  enabled: true
  sampler:
    percentage: 1
  zipkin:
    enabled: true
    baseUrl: http://${tracking-host:tracking}:9411